### ISSUE TITLE
Set `ScanPolicy` to 0

### ISSUE THREAD

**Issue by jbritain** [w43322/X220-OpenCore#1]
Set up as described, booted into OpenCore, and the only option that appeared was `openshell.efi`.

From a quick google, one person suggested setting `ScanPolicy` to 0. Doing this allowed the installer to show up. I thought it would be worthwhile setting this in the main repo in case anyone else has this issue in future,

Thanks for the EFI, btw! The guide contradicts itself at times and I couldn't quite get OC working myself, so this saved me a lot of time!

**Comment by w43322** [comment]
No problem, thanks for the input, I will change it in the repo once I have some spare time.

Btw, you can press spacebar to reveal the installer on the USB. OpenCore doesn't show external boot entries by default for security reasons I believe.

**Comment by jbritain** [comment]
I did try pressing the space bar, but to no avail
